runtime: php83  # 選擇 PHP 8.3 執行環境

instance_class: F2  # 指定實例類型 (依需求調整)
entrypoint: php -S 0.0.0.0:8080 -t vendor/smokedgoose/wordpress

env_variables:
  # WordPress 與 Cloud SQL 的相關設定
  DB_NAME: 'wordpress'
  DB_USER: 'karl'
  DB_PASSWORD: 'Aa3345678'
  DB_HOST: 'local.bgmotion.com.tw:3333'

handlers:
  # 讓 WordPress 正常處理請求
  - url: /.*
    script: auto
    secure: always